"""empty message

Revision ID: 67990ec5adc8
Revises: c3a7dbbab757
Create Date: 2023-04-13 21:40:54.225470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67990ec5adc8'
down_revision = 'c3a7dbbab757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
